[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
id3 = "1.13.1"
mp3-duration = "0.1.10"
rdev = "0.5.3"
rodio = { version = "0.18.1", features = ["minimp3"], default-features = false }
spin_sleep = "1.2.0"

[target.'cfg(target_os = "linux")'.dependencies]
xosd-rs = "0.2.0"
