[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
id3 = "1.13.1"
rdev = "0.5.3"
rodio = "0.18.1"
spin_sleep = "1.2.0"

[target.'cfg(target_os = "linux")'.dependencies]
xosd-rs = "0.2.0"

# [target.'cfg(target_os = "windows")'.dependencies]
# native-windows-gui = "1.0.13"
# native-windows-derive = "1.0.5"
