[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
id3 = "1.13.1"
rdev = "0.5.3"
spin_sleep = "1.2.0"
playback-rs = "0.4.4"

[target.'cfg(target_os = "linux")'.dependencies]
xosd-rs = "0.2.0"

[patch.crates-io]
playback-rs = { git = "https://github.com/feois/playback-rs-fork.git" }
